### ISSUE TITLE
Displaying 10/2018

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.versions#268]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

If the date attribute was 2018-10-00 or 2018-10, the system at some point gave it a collection date 2018-09-30.

Check if this is still the case or if the system is now correctely showing it as 10/2018 which would be more logical as the data had been collected in October.

Minor issue.

**Comment by john-shepherdson** [comment]
Check if fixed

**Comment by matthew-morris-cessda** [comment]
See https://datacatalogue-dev.cessda.eu/detail?lang=en&q=3ee70237176c9a2423b2a34befcb8dca49ebe3f5bfaba253221253bfc9c0f6d1 for another example
