### ISSUE TITLE
Index and User Guide texts overlapping in UI

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.versions#271]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

[https://datacatalogue-staging.cessda.eu/documentation/basic-search.html](https://datacatalogue-staging.cessda.eu/documentation/basic-search.html)

The index \(the table of contents\) on the left and the User Guide text on the right are overlapping if you use half-screen view. Does this matter?

**Comment by john-shepherdson** [comment]
@KristinaS4 Can you check if this is still a problem? I don't run Firefox

**Comment by KristinaS4** [comment]
@john-shepherdson I checked this with Firefox in split screen view and it does not appear to be a problem.

**Comment by john-shepherdson** [comment]
Thanks Kristina
