### ISSUE TITLE
Creator identifier (e.g. ORCID)

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.versions#290]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

Show creator identifier if available in metadata.

Waits for DDI 2.6. Before that no element in metadata.

**Comment by matthew-morris-cessda** [comment]
See https://github.com/cessda/cessda.metadata.profiles/issues/162 for what this looks like in DDI

**Comment by john-shepherdson** [comment]
`<rspStmt>
<AuthEnty affiliation="Kansalliskirjasto" xml:lang="fi" >Mikkonen, Jukka
<ExtLink URI="https://orcid.org/0000-0003-0436-8526" role="PID" title="ORCID" xml:lang="fi" >0000-0003-0436-8526</ExtLink>
</AuthEnty>
<AuthEnty affiliation="National Library of Finland" xml:lang="en" >Mikkonen, Jukka
<ExtLink URI="https://orcid.org/0000-0003-0436-8526" role="PID" title="ORCID" xml:lang="en" >0000-0003-0436-8526</ExtLink>
</AuthEnty>
</rspStmt>`

**Comment by matthew-morris-cessda** [comment]
I'll modify cessda.cdc.searchkit to emulate the current behavior

**Comment by MortenSikt** [comment]
With regards to UI label here for the information.

If the content is only validated against ORCID, then ORCID as label makes sense.

If there is other personal identifiers used here (unknown to me) then the DDI attribute name Personal ID can be used.

Thirdly, creators can be organizations (without an individual person attached) and these can have identifiers, ROR. Then Personal ID label is not covering enough. I am unsure if this is used & provided by any SP.

**Comment by markusjt** [comment]
> If the content is only validated against ORCID, then ORCID as label makes sense.

Found identifiers are indexed with id (mandatory), type (optional) and uri (optional). This means it should be more generic so we can show the identifier anyway even if we don't know its type and can't add hyperlink (uri) on it. Unless we decide to only show identifiers that we know the type of so we could then add label accordingly? Not sure if that's a good idea though.

> Thirdly, creators can be organizations (without an individual person attached) and these can have identifiers, ROR. Then Personal ID label is not covering enough. I am unsure if this is used & provided by any SP.

FSD is planning on adding ROR identifiers at some point as far as I know but I'm not sure when. I think it would be a good idea to already prepare for them anyway since they will be provided sooner or later (and probably sooner).

Maybe always label it "Research Identifier"? Similar but longer option would be "Research Entity Identifier" but I feel like "Research Identifier" would suffice.

**Comment by MortenSikt** [comment]
I like the suggestion "Research Identifier" so think that would be good.

Out of curiosity would you know how DDI-L identifiers would be handled? these are not exactly intended for this purpose, at least not in our or European Sosical Survey case.

**Comment by markusjt** [comment]
I'm not too familiar with DDI-L but I can see that the way Matthew has done it is to parse the id, type and uri from [ResearcherID](https://ddialliance.org/Specification/DDI-Lifecycle/3.3/XMLSchema/FieldLevelDocumentation/schemas/archive_xsd/elements/ResearcherID.html) element (ResearcherIdentification, TypeOfID and URI).

I was about to start working on this but then I immediately realized that there can be multiple creators so how do we actually display these identifiers clearly? Just list them in the same order under the Research Identifier label? Or think of a way to show them next to the identifier? One way would be to do what FSD has done and just add it as a link on the creator's name ([example](https://services.fsd.tuni.fi/catalogue/FSD3766?lang=en&study_language=en)) but that would only work for identifiers that have uri specified.

**Comment by MortenSikt** [comment]
> I'm not too familiar with DDI-L but I can see that the way Matthew has done it is to parse the id, type and uri from [ResearcherID](https://ddialliance.org/Specification/DDI-Lifecycle/3.3/XMLSchema/FieldLevelDocumentation/schemas/archive_xsd/elements/ResearcherID.html) element (ResearcherIdentification, TypeOfID and URI).
> 

That is a different element than what I was thinking about so it should be fine then. Thanks for that

> I was about to start working on this but then I immediately realized that there can be multiple creators so how do we actually display these identifiers clearly? Just list them in the same order under the Research Identifier label? Or think of a way to show them next to the creator name? One way would be to do what FSD has done and just add it as a link on the creator's name ([example](https://services.fsd.tuni.fi/catalogue/FSD3766?lang=en&study_language=en)) but that would only work for identifiers that have uri specified.

Not sure a list in the same order would be a good solution, there might be some creators that have and some that don't so the list might not be in sync.

Is it possible to add this within the creator box:

![bilde](https://github.com/cessda/cessda.cdc.versions/assets/116061162/9f4f38c9-f7ec-4070-980b-b011a62657aa)

With a hyphen "-" sign and then the label "Research Identifier": the actual identifier? 

Similar to what is done in [AUSSDA's dataverse](https://data.aussda.at/dataset.xhtml?persistentId=doi:10.11587/GCSLIN): 
![bilde](https://github.com/cessda/cessda.cdc.versions/assets/116061162/9dec97eb-ed8e-4d63-a6c1-239ebd074867)

except they have ORCID as label.

Then we can also do as Dataverse that the identifier is clickable if a uri is specified. This uri should probably be opened in a new tab/window with an indiciation that it is an external link. Same as we have done for the ELSST links

**Comment by markusjt** [comment]
That sounds good. I'll add them like that. We could add a type check for the label so it would say ORCID if the identifier has type specified as ORCID. Of course this would mean that sometimes it would say Research Identifier even though it's clearly ORCID if it's not specified in the metadata since I'd prefer not adding any convoluted format checking and only checking against the actual type information from metadata.
