### ISSUE TITLE
Add user search queries to dashboard

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.versions#355]
**Original report on BitBucket by John Shepherdson (GitHub: [john-shepherdson](https://github.com/john-shepherdson)).**

----------------------------------------

As the CTO, I want to see how many search queries the CDC & CDC API each have answered in the timeframe \[x:y\]

‌

**Comment by john-shepherdson** [comment]
Check if done

**Comment by matthew-morris-cessda** [comment]
Done in `ui_response_time_duration`
