### ISSUE TITLE
SP feedback on CDC search - summary

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.versions#377]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

Summary of results from the survey conducted by CDC Upgrade project:

**Improvements of user experience:** 

* access data button should be more highlighted: solved: https://github.com/cessda/cessda.cdc.versions/issues/340
* shorter abstract on results page: solved: https://github.com/cessda/cessda.cdc.versions/issues/414
* scrolling down the list of studies on the result page, the filters on the left should not disappear: solved: https://github.com/cessda/cessda.cdc.versions/issues/473
* add a demonstration video on how to use the catalogue: we have two: https://www.youtube.com/watch?v=THiYtgsrzF4 and https://www.youtube.com/watch?v=o_vSVIz03vs
* PIDs and other DOIs \(DAI, ORCIDs\) should be executable: executable through "Access study button"
* language selection issues reported: Unsure what this refers to, cant find any open issues on it.
* similar studies list: should include all studies in the catalogue and not only studies by the individual SP: Checked, and not an issue

Just copying these for future discussion.

**Comment by MortenSikt** [comment]
Closing this as most is resolved, and it is unclear what the others refer to.
