### ISSUE TITLE
Configure rate limiting for search API

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.versions#408]
**Original report on BitBucket by John Shepherdson (GitHub: [john-shepherdson](https://github.com/john-shepherdson)).**

----------------------------------------

Protection from DOS attacks, via HaProxy

**Comment by matthew-morris-cessda** [comment]
Resolved as of https://github.com/cessda/cessda.cdc.reverse/commit/66f5c1df80e132dbf39f655de6c8199d3e6345ec
