### ISSUE TITLE
Cut-off long abstracts at full word

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.versions#436]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

We have a character limit point after which long abstracts are cut off in detailed study view.

It would be better if the cut-off was done at full word, if possible. Three dots still needed.

Related to resolved #414.

**Comment by markusjt** [comment]
This has actually already been done at some point.

Abstract is truncated by [truncate from lodash](https://lodash.com/docs/4.17.15#truncate) with the separator option: _[options.separator] (RegExp|string): The separator pattern to truncate to._
```
import { truncate, upperFirst } from 'lodash';
...
function truncateAbstract(string: string): string {
  const trimmedString = string.trim();
  return truncate(trimmedString, { length: 500, separator: ' ' } );
}
```
