### ISSUE TITLE
[Handler - DDI 2.5] Make Update to concept lang Extraction

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.versions#44]
**Original report on BitBucket by Moses Mansaray (GitHub: [doraVentures](https://github.com/doraVentures)).**

----------------------------------------

>-          Moving the xml:lang to the element itself (instead of <concept>) in timeMeth, collDate, sampProc and anlyUnit and amending the xml examples accordingly.

Source: 

- Type: email 
- From: Taina
- subject: Updating PaSC documents

**Comment by matthew-morris-cessda** [comment]
This is a CMM topic and is not relevant here
