### ISSUE TITLE
CDC Aggregator usage stats

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.versions#446]
**Original report on BitBucket by John Shepherdson (GitHub: [john-shepherdson](https://github.com/john-shepherdson)).**

----------------------------------------

What is possible to count? 

Base URL:

* Endpoint is being called

Use of the verbs: 

* GetRecord – Used to retrieve an individual metadata record.
* Identify – Used to retrieve repository information \(ex. name, version\).
* ListIdentifiers – Used to retrieve only headers.
* ListMetadataFormats – Used to retrieve the available metadata formats.
* ListRecords – Used to retrieve actual item metadata records.
* ListSets – Used to retrieve the set structure of a repository

Arguments used with verbs:

* identifier
* metadataPrefix
* from
* until
* set
* resumptionToken

Anything else?

**Comment by toni-sissala** [comment]
Added issue to aggregator oai-pmh repo handler issue tracker at https://github.com/cessda/cessda.cdc.aggregator.oai-pmh-repo-handler/issues/43

**Comment by john-shepherdson** [comment]
@Joshua-cessda-admin Are you getting the info you need? Please add feedback to this issue

**Comment by matthew-morris-cessda** [comment]
This has been implemented, further changes should be filed as a new issue
