### ISSUE TITLE
Make Feedback button more visible

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.versions#452]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

People do not notice it.

**Comment by john-shepherdson** [comment]
26/07/2023 (from email exchange):

Hi,

I agree, the feedback button now looks much better and should be easier to notice in the blue colour.

The feedback form also looks good with the new changes. I don’t think you need to change anything else, and I think it’s not worth spending more time on this as both feedback button and form looks good now.

About the other placeholders in CDC, would you then replace them with text somewhere else or just remove them altogether?

Kristina
