### ISSUE TITLE
Restyle feedback form

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.versions#468]
**Original report on BitBucket by John Shepherdson (GitHub: [john-shepherdson](https://github.com/john-shepherdson)).**

----------------------------------------

Switch from Jira to Zammad issue collect has resulted in a bare-bones form for users to complete.

![](https://bitbucket.org/repo/oLgpneG/images/3642925221-Screenshot%202022-09-14%20at%2011.37.39.png)
If should be restyled to make it more visually appealing.

**Comment by MortenSikt** [comment]
Do we have example on old Jira form that was more visually appealing? In order to "flesh it out"
