### ISSUE TITLE
Clicking on a keyword in summary information view should search keyword element only

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.versions#488]
**Original report on BitBucket by John Shepherdson (GitHub: [john-shepherdson](https://github.com/john-shepherdson)).**

----------------------------------------

In CDC UI when the user clicks on a keyword, the system executes a phrase search and gives results regardless of in which field the phrase occurred. Could this now be changed so that the system would make the phrase search in the keyword element only?

**Comment by matthew-morris-cessda** [comment]
These issues are things like differences in spelling (i.e. American/British English variations). Labor/labour is a good example of this. The example image of the filter didn't survive the GitHub migration, so I've recreated it. I've also linked the development branch to this issue.

![image](https://user-images.githubusercontent.com/68543725/235615215-3c396bc9-7c53-4899-a1bc-6c617157fafc.png)

**Comment by MortenSikt** [comment]
Yes, that makes sense. Looking at ELSST the language tag for english is just "en" so there both could be included. But seeing as UKDA is responsible for the English version of the thesaurus one would assume that British English is implemented for all terms. 

I am unaware if any SP edit ELSST after they import it to their systems, but if they are doing that the thesaurus is something else than ELSST. All translations/edits should be made by and within the ELSST group and tied to a specific version of the thesaurus 

The failproof, and perhaps correct way, would be to use the identifiers for the term. But I am unsure how many SPs actually provide this information in their records. So implementing this as you suggest seems to be the most feasible.

I think if cases occur where there is difference in spelling, we as the Service Owner, should contact the metadata person for their SP to correct the issue. 

There is also the case where SPs might use other keywords than those present in ELSST, not sure if it is possible to exclude those from the filter in any way. But it might not be the worst if these also can be used as filter, although they might sometimes just result in one study.
