### ISSUE TITLE
Improve Harvester SQA rating

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.versions#489]
**Original report on BitBucket by John Shepherdson (GitHub: [john-shepherdson](https://github.com/john-shepherdson)).**

----------------------------------------

Various non-functional additions and changes to improve the SQA rating, as given by the SQAaaS tool \([https://sqaaas.eosc-synergy.eu/#/auth/full-assessment](https://sqaaas.eosc-synergy.eu/#/auth/full-assessment)\)

**Comment by toni-sissala** [comment]
I'll start working with this tomorrow. I have cloned the repo "cessda.metadata.harvester" and managed to get a checkstyle report by running the checkstyle maven plugin:
```
mvn checkstyle:checkstyle
```

It outputs 1743 errors using sun_checks.xml ruleset. I had a look at the error messages and I think I can solve a large number of reported errors.

Is the sun_checks.xml ruleset (Sun Microsystems Definition) ok or should I use a different one?

The checkstyle report does not give any output regarding the Changelog.md file or its line length. How should I get that checked, so I can make proper changes?

I see that the repo already has a properly formatted tag '3.2.1'. There is also a fix in pom.xml for the maven-release-plugin (https://github.com/cessda/cessda.metadata.harvester/commit/92ef83d541e66d874db71ae3c44fb906cefed814). I think there is no work to be done here.

**Comment by john-shepherdson** [comment]
I reran the SQAaaS tool today. I will send you the report for reference (I cannot see how to attach it to this issue).

- [ ] add CONTRIBUTING.md file (see e.g. /cessda.cdc.searchkit)
- [ ] markdownlint errors (details below)
- [ ] Checkstyle errors (1,743) (suggest you only fix the ones that are easily done with find and replace)
- [X] Not all release tags are SemVer compliant (unfortunately it checks them all, nothing can be done to fix this)
- [ ] Add CITATION.cff file (see e.g. /cessda.cdc.searchkit)
- [X] Code fails Static Analysis Security Testing (this is a shortcoming of the SQAaaS tool, it can only check Python and GO executables)

**Comment by john-shepherdson** [comment]
markdownlint errors (max line length is 80 chars)

{
	"./CHANGELOG.md": {
		"MD004": {
			"description": "Unordered list style",
			"line": [
				153
			]
		},
		"MD007": {
			"description": "Unordered list indentation",
			"line": [
				125
			]
		},
		"MD010": {
			"description": "Hard tabs",
			"line": [
				125,
				126,
				127,
				128,
				129,
				130,
				131,
				132,
				133
			]
		},
		"MD013": {
			"description": "Line length",
			"line": [
				25,
				33,
				39,
				58,
				73,
				79,
				114,
				123,
				153
			]
		},
		"MD024": {
			"description": "Multiple headers with the same content",
			"line": [
				37,
				43,
				51,
				56,
				62,
				71,
				81,
				85,
				93,
				101,
				108,
				112,
				116,
				135,
				143,
				147
			]
		}
	},
	"./CONTRIBUTORS.md": {
		"MD033": {
			"description": "Inline HTML",
			"line": [
				1,
				1
			]
		}
	},
	"./README.md": {
		"MD009": {
			"description": "Trailing spaces",
			"line": [
				10,
				24,
				81,
				101,
				114,
				182
			]
		},
		"MD012": {
			"description": "Multiple consecutive blank lines",
			"line": [
				37
			]
		},
		"MD013": {
			"description": "Line length",
			"line": [
				12,
				24,
				30,
				34,
				44,
				46,
				47,
				48,
				49,
				50,
				51,
				52,
				54,
				58,
				72,
				74,
				87,
				91,
				93,
				107,
				125
			]
		},
		"MD022": {
			"description": "Headers should be surrounded by blank lines",
			"line": [
				1
			]
		}
	}
}

**Comment by toni-sissala** [comment]
Thank you, John!

I guess the checkstyle ruleset is the sun_checks.xml, since I'm getting the same count of overall errors.

Anyway, now I have enough info to get started.

**Comment by toni-sissala** [comment]
Here is a PR addressing these issues. https://github.com/cessda/cessda.metadata.harvester/pull/13

**Comment by john-shepherdson** [comment]
I did not realise that line length can be set in POM file.
See https://docs.sqaaas.eosc-synergy.eu/quality_assessment_and_awarding/customize/#checkstyle-java
We use 140 chars for linting Markdown docs, could use same for Java

**Comment by john-shepherdson** [comment]
Code has been awarded SQAaaS Silver badge, please add this snippet to top of README file

[![SQAaaS badge](https://github.com/EOSC-synergy/SQAaaS/raw/master/badges/badges_150x116/badge_software_silver.png)](https://api.eu.badgr.io/public/assertions/4MtipH8nTG-1OC0hjsZQ5A "SQAaaS silver badge achieved")

**Comment by john-shepherdson** [comment]
No Gold, as failed on codestyle and security. At present, SQAaaS cannot do static security analysis on Java executables, so this will never pass. The Java lint issues have been discussed above, no further action required.

You may want to  fix the one Markdown lint issue:

{
	"./CHANGELOG.md": {
		"MD007": {
			"description": "Unordered list indentation",
			"line": [
				141
			]
		}
	}
}

**Comment by john-shepherdson** [comment]
Validation is via the SQAaaS tool (https://sqaaas.eosc-synergy.eu/#/auth/full-assessment)

This is correct according to Visual Studio Code - I removed one space to the left of each item in the sublist:

- Configurations for
  - CSDA
  - DANS
  - DBK
  - DNA
  - EKKE
  - FSD
  - NSD
  - SND
  - UKDA

**Comment by toni-sissala** [comment]
I had a look at this again. It seems that the SQA tool uses older version (0.11.0) of mdl (https://github.com/EOSC-synergy/sqaaas-tooling/blob/main/tooling.json#L459), which defaults to indent of 2 spaces. Should we comply to the default ruleset of the 0.11.0 version? If so, I propose adding the indent level to the file .mdl_custom_style.rb, so that if the SQA tool should upgrade to 0.12.0 or beyond, we would still comply to the ruling.

I also noticed that there is now another issue in CHANGELOG.md in main branch:

```
$ mdl CHANGELOG.md 
CHANGELOG.md:33: MD013 Line length
```

I think the markdownlint check should be added to the Jenkins job, so that whenever a PR is evaluated, Jenkins would nag about possible formatting issues in markdown files.

**Comment by john-shepherdson** [comment]
We should take the path of least effort for these relatively trivial matters, so add the intent level to the custom style file.

@matthew-morris-cessda please look at adding the Markdown check to the Jenkins job

**Comment by john-shepherdson** [comment]
Badge text
[![SQAaaS badge shields.io](https://img.shields.io/badge/sqaaas%20software-silver-lightgrey)](https://eu.badgr.com/public/assertions/4MtipH8nTG-1OC0hjsZQ5A "SQAaaS silver badge achieved")

**Comment by john-shepherdson** [comment]
Check recommendations and PRs

**Comment by toni-sissala** [comment]
I checked the PRs and they have been merged.

**Comment by john-shepherdson** [comment]
Now merged
