### ISSUE TITLE
Remove DNA metadata from CDC

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.versions#503]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

The Daninsh endpoint it seems has not been updated with new metadata for some years. Most recent dataset seems to be 11 years old.

Is it misleading to leave it in the CDC as people might think there is no data on the subject in Denmark? Should it be dropped? My own inclination would be to drop it in 2023 but leaving the decision for the future SO.

To be discussed in CDC User Group.

**Comment by matthew-morris-cessda** [comment]
DNA has been removed from the dev and staging instances of CDC by using Elasticsearch's [delete by query](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/docs-delete-by-query.html) API.

The precise query used was:

`POST /cmmstudy_*/_delete_by_query`

```json
{
    "query": {
        "term": {
            "code": {
                "value": "DNA"
            }
        }
    }
}
```

**Comment by john-shepherdson** [comment]
Pending general policy decision by SPF

**Comment by john-shepherdson** [comment]
See also https://github.com/cessda/cessda.cvs.two/issues/898 re DNA data in CVS, on the basis that when either is agreed, both can be done.

**Comment by alen-vodopijevec-cessda** [comment]
@matthew-morris-cessda, you can remove DNA data from CDC production.

**Comment by matthew-morris-cessda** [comment]
Will be removed after 3.7.0 is released

**Comment by matthew-morris-cessda** [comment]
DNA metadata has been removed from the CESSDA Data Catalogue
