### ISSUE TITLE
Update SIKT endpoint details

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.versions#505]
**Original report on BitBucket by John Shepherdson (GitHub: [john-shepherdson](https://github.com/john-shepherdson)).**

----------------------------------------

Here are OAI-PMH endpoints –

1. ESS : [https://colectica-ess-published.nsd.no/oai/request?verb=Identify](https://colectica-ess-published.nsd.no/oai/request?verb=Identify)
2. Norwegian Research Data Archive: [https://colectica-forskningsdata-published.nsd.no/oai](https://colectica-forskningsdata-published.nsd.no/oai)  \( this sometimes gets 502 error due to performance issues, but upon retrying connects successfully\)

The ESS metadata is structured as a series. That means that all ESS metadata is available under one item:

[https://colectica-ess-published.nsd.no/oai/request?verb=ListIdentifiers&set=4bd6eef6-99df-40e6-9b11-5b8f64e5cb23](https://colectica-ess-published.nsd.no/oai/request?verb=ListIdentifiers&set=4bd6eef6-99df-40e6-9b11-5b8f64e5cb23)

It’s also possible to harvest each study individually if this is easier to manage for you. For ESS we have 10 studies:

[https://colectica-ess-published.nsd.no/oai/request?verb=ListIdentifiers&set=30ea0200-7121-4f01-8d21-a931a182b86d](https://colectica-ess-published.nsd.no/oai/request?verb=ListIdentifiers&set=30ea0200-7121-4f01-8d21-a931a182b86d)

**Comment by matthew-morris-cessda** [comment]
ESS appears to return partial records for GetRecord requests, resulting in invalid XML. See https://colectica-ess-published.nsd.no/oai/request?verb=GetRecord&metadataPrefix=oai_ddi33&identifier=int.esseric:2582f727-de3d-4f09-a222-e46fa2c904be:3 which returns:

```xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type='text/xsl' href='/oai/oai-pmh.xsl'?>
<oai:OAI-PMH xmlns:oai="http://www.openarchives.org/OAI/2.0/">
  <oai:responseDate>3/9/2023 12:42:31 PM</oai:responseDate>
  <oai:request p2:verb="http://www.openarchives.org/OAI/2.0/" xmlns:p2="GetRecord">/oai/request</oai:request>
  <oai:GetRecord>
    <oai:record>
      <oai:header>
        <oai:identifier>int.esseric:2582f727-de3d-4f09-a222-e46fa2c904be:3</oai:identifier>
        <oai:datestamp>2023-01-25T22:23:38.9525250</oai:datestamp>
        <oai:setSpec>e99acc19-d127-413d-9cf9-aed786e62055</oai:setSpec>
      </oai:header>
      <oai:metadata>
```

**Comment by john-shepherdson** [comment]
On Tue, 26 Sept 2023 at 09:23, Archana Bidargaddi wrote:

Hi John,

Really long since we followed up on the OAI-PMH endpoint and harvesting of our metadata by CESSDA.

We have now upgraded our repositories to Colectica 7.2 version and wanted to know if you have been able to successfully harvest our metadata.

Do let us know if you need anything from us.

--

Med vennlig hilsen

Archana Bidargaddi

**Comment by john-shepherdson** [comment]
I have just checked the development and production storage buckets for Sikt and there are no content in either. This is due to endpoint config being commented out in https://github.com/cessda/cessda.cdc.aggregator.deploy/blob/main/charts/harvester/config/config.yaml

**Comment by john-shepherdson** [comment]
https://colectica-forskningsdata-published.nsd.no/oai/request?verb=Identify
![Screenshot 2023-10-04 at 14 49 45](https://github.com/cessda/cessda.cdc.versions/assets/107628491/c7b1079d-17c2-46ba-85ce-d6565782c63c)

**Comment by john-shepherdson** [comment]
https://colectica-ess-published.nsd.no/oai/request?verb=Identify
![Screenshot 2023-10-04 at 14 52 23](https://github.com/cessda/cessda.cdc.versions/assets/107628491/d5fcc623-29cc-4c53-8ee7-5bcd8c48ff74)

**Comment by john-shepherdson** [comment]
See https://github.com/cessda/cessda.cdc.aggregator.deploy/pull/9

**Comment by matthew-morris-cessda** [comment]
Sikt's OAI-PMH endpoint only returns partial responses when requesting a record with GetRecord. This causes compliant XML parsers to fail as XML tags must be closed.

![image](https://github.com/cessda/cessda.cdc.versions/assets/68543725/a5e2db76-1933-42f6-bcfb-9a9917ff1748)

An example XML response is below, along with a comment specifying where the missing closing tag should be.

```xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type='text/xsl' href='/oai/oai-pmh.xsl'?>
<oai:OAI-PMH xmlns:oai="http://www.openarchives.org/OAI/2.0/">
  <oai:responseDate>3/8/2024 1:43:52 PM</oai:responseDate>
  <oai:request p2:verb="http://www.openarchives.org/OAI/2.0/" xmlns:p2="GetRecord">/oai/request</oai:request>
  <oai:GetRecord>
    <oai:record>
      <oai:header>
        <oai:identifier>no.nsd:376e8395-5869-44d4-96b4-6455232f1bad:1</oai:identifier>
        <oai:datestamp>2024-03-04T13:52:25.9310840</oai:datestamp>
        <oai:setSpec>7e47c269-bcab-40f7-a778-af7bbc4e3d00</oai:setSpec>
      </oai:header>
      <oai:metadata>
<ddi:FragmentInstance xmlns:r="ddi:reusable:3_3" xmlns:ddi="ddi:instance:3_3">
  <ddi:TopLevelReference>
    <r:Agency>no.nsd</r:Agency>
    <r:ID>376e8395-5869-44d4-96b4-6455232f1bad</r:ID>
    <r:Version>1</r:Version>
    <r:TypeOfObject>Category</r:TypeOfObject>
  </ddi:TopLevelReference>
<Fragment xmlns:r="ddi:reusable:3_3" xmlns="ddi:instance:3_3">
  <Category isUniversallyUnique="true" versionDate="2024-02-19T12:14:23.7628656Z" isMissing="false" xmlns="ddi:logicalproduct:3_3">
    <r:URN>urn:ddi:no.nsd:376e8395-5869-44d4-96b4-6455232f1bad:1</r:URN>
    <r:Agency>no.nsd</r:Agency>
    <r:ID>376e8395-5869-44d4-96b4-6455232f1bad</r:ID>
    <r:Version>1</r:Version>
    <r:VersionResponsibility>SIKT\chege</r:VersionResponsibility>
    <r:VersionRationale>
      <r:RationaleDescription>
        <r:String xml:lang="no">Lagt inn datasettet i colectica, klargjort for dokumentering</r:String>
      </r:RationaleDescription>
    </r:VersionRationale>
    <r:Label>
      <r:Content xml:lang="no">100.000 - 149.000</r:Content>
    </r:Label>
  </Category>
</Fragment>
</ddi:FragmentInstance>
      </oai:metadata>
<!-- </oai:OAI-PMH> should be here, but isn't -->
```
