### ISSUE TITLE
Add FORS endpoint

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.versions#506]
**Original report on BitBucket by John Shepherdson (GitHub: [john-shepherdson](https://github.com/john-shepherdson)).**

----------------------------------------

* We have not yet implemented Dublin Core support \(oai\_dc\), I hope this is not a problem ?
* We have not yet implemented all the fields from the CMM, but of course, all the required ones \+ some recommended / optional
* Our OAI-PMH endpoint is not yet running in production, but it can be made available at almost any time

Here is our endpoint from our TEST system: [https://tst.swissubase.ch/oai-pmh/v1/oai](https://tst.swissubase.ch/oai-pmh/v1/oai)

**Comment by john-shepherdson** [comment]
Closed by #524
