### ISSUE TITLE
Add Object Identifier of validated records to the CMV logs

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.versions#514]
**Original report on BitBucket by Matthew Morris (GitHub: [matthew-morris-cessda](https://github.com/matthew-morris-cessda)).**

----------------------------------------

From Joshua:

> This is helpful to compare and see if there is a correlation between the failed records and low fuji score

This involves adding the record identifier to the output.

**Comment by matthew-morris-cessda** [comment]
@Joshocan This is now implemented

**Comment by matthew-morris-cessda** [comment]
Reopening as the implementation needs to be changed to read the URL from the XML.
