### ISSUE TITLE
Enable word clouds to be generated using Kibana

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.versions#516]
**Original report on BitBucket by Matthew Morris (GitHub: [matthew-morris-cessda](https://github.com/matthew-morris-cessda)).**

----------------------------------------

This involves adding a new field to the Elasticsearch index to store the keywords in the root document. This is needed because Kibana cannot use nested fields as a source for visualisations.

**Comment by matthew-morris-cessda** [comment]
The new field was merged in https://github.com/cessda/cessda.cdc.osmh-indexer.cmm/commit/4ffe0b7127d467332bab3fc3d99fb0c09d57e880
