### ISSUE TITLE
Update list of harvested endpoints

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.versions#524]
**Original report on BitBucket by John Shepherdson (GitHub: [john-shepherdson](https://github.com/john-shepherdson)).**

----------------------------------------

Remove DNA \(ex-member\);

Use FORS production endpoint;

Remove NESSTAR endpoints \(NSD, CSDA\);

Delete DNA and FORS files, keep NSD/SIKT and CSDA files

**Comment by MortenSikt** [comment]
I am still seeing records from DNA in the catalogue (https://datacatalogue-staging.cessda.eu/?publisher.publisher[0]=Danish%20National%20Archives%20%28DNA%29), should they not be removed?

![image](https://user-images.githubusercontent.com/116061162/227921392-4ed9fb2d-64d6-457b-ba18-2564f8f4ca24.png)

**Comment by john-shepherdson** [comment]
@matthew-morris-cessda please delete harvested files for DNA and perform a (partial) re-index to remove them from the UI.

What about the Aggregator?

**Comment by john-shepherdson** [comment]
DNA ceased to be a Service Provider at the end of 2022.

**Comment by john-shepherdson** [comment]
OK, for now the harvested files for DNA will remain, but the harvesting stops.
