### ISSUE TITLE
BASE Requirement: Incorrect Specification to some of CESSDA Records

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.versions#525]
**Original report on BitBucket by Joshua Tetteh Ocansey (GitHub: [Joshocan](https://github.com/Joshocan)).**

----------------------------------------

From BASE : 

“ The URL in <dc:identifier> lack correct links to the article frontdoor. In <dc:identifier> there is an entry like:

10\.20366/unimib/unidata/SN236-1.0

In our search engine BASE only documents can get indexed whose identifiers begin with http:, https:, doi:

The URL in <dc:identifier> should like

[https://doi.org/10.20366/unimib/unidata/SN236-1.0](https://doi.org/10.20366/unimib/unidata/SN236-1.0)  
or  
doi:10.20366/unimib/unidata/SN236-1.0

Can you update your identifiers accordingly? “

‌

**Comment by toni-sissala** [comment]
Here is some background info and changes that were agree to on March 13th 2023 during CDC spring meeting.

BASE requires that oai-dc serialization should have a dc:identifier, whose value is a DOI represented as URL or prefixed by "doi:". The given example entry is "10.20366/unimib/unidata/SN236-1.0". The example DOI points to "Italian Lives – ITA.LI (2019-2021)" study landing page. The DDI-metadata for the example study is available via OAI-PMH from the aggregator at https://datacatalogue.cessda.eu/oai-pmh/v0/oai?verb=GetRecord&metadataPrefix=oai_ddi25&identifier=cff5a3e2f139055aa78471d3011d56f44add16d0145d47b5c0d9155c1e842918 and its source OAI-PMH is at http://oai.unidata.unimib.it/v0/oai?verb=GetRecord&metadataPrefix=oai_ddi25&identifier=SN226

The source (and the aggregator) has the DOI represented as a URL at XPATH /codeBook/stdyDscr/citation/holdings/@URI, which is also a mandatory element according to CDC profile for DDI2.5. (see https://cmv.cessda.eu/profiles/cdc/ddi-2.5/1.0.4/profile.html).

The proposed change to fulfill the requirement for BASE is to use the holdings/@URI value for dc:identifier. This way the aggregator does not need to alter any metadata values or impose new requirements to the SP. However, the proposed fix will only work for cases like the example given in the issue description. If, for example, some SPs do not have any suitable DOI value in their metadata, their metadata in the aggregator will remain incompatible with BASE requirements.

It was decided that Aggregator's OAI-DC serialization shall include /codeBook/stdyDscr/citation/holdings/@URI as a source for the value for dc:identifier.

**Comment by toni-sissala** [comment]
The proposed change is implemented and released in cessda.cdc.aggregator.oai-pmh-repo-handler version 0.5.0
