### ISSUE TITLE
Update the validator to use the latest version of the CDC DDI 2.5 validation profiles

### ISSUE THREAD

**Issue by matthew-morris-cessda** [cessda/cessda.cdc.versions#546]
This profile contains changes to allow DDI generated from Dataverse to pass validation.

**Comment by MortenSikt** [comment]
https://github.com/cessda/cessda.metadata.profiles/issues/149 issue for editing xml:lang . I am unable to add labels and assign in that repo

**Comment by matthew-morris-cessda** [comment]
Thanks Morten. I've assigned the issue to myself and will update you soon.

**Comment by matthew-morris-cessda** [comment]
See https://github.com/cessda/cessda.cmv.server/issues/126

**Comment by matthew-morris-cessda** [comment]
Given that the updated profile is ready to release and the validator is configured to use it, I'm closing this issue.

**Comment by MortenSikt** [comment]
We are still seeing the 1.0.4 profiles at the CMV webpage: https://cmv.cessda.eu/documentation/profiles.html with the profiles available there specifying mandatory for xml:lang. Is this intended?

**Comment by matthew-morris-cessda** [comment]
This is correct. I haven't released these profiles yet. I'll update this issue when this occurs.

**Comment by matthew-morris-cessda** [comment]
Profiles have been updated
