### ISSUE TITLE
Add CSDA Dataverse endpoint

### ISSUE THREAD

**Issue by john-shepherdson** [cessda/cessda.cdc.versions#549]
ADD:
  - url: https://archivdv.soc.cas.cz/oai
      code: CSDA
      name: "Czech Social Science Data Archive (ČSDA)"
      validationGate: BASIC
      metadataPrefixes:
        - metadataPrefix: oai_ddi
          setSpec: CSDA_EN
          ddiVersion: DDI_2_5
          validationProfile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml

**Comment by john-shepherdson** [comment]
OAI-PMH validator results

![Screenshot 2023-05-25 at 15 27 54](https://github.com/cessda/cessda.cdc.versions/assets/107628491/be87989b-394b-4a9a-81ac-e3198f3ad980)

![Screenshot 2023-05-25 at 15 29 32](https://github.com/cessda/cessda.cdc.versions/assets/107628491/3b8e5c66-6216-4c1d-9a6c-11de3e77d5e3)

**Comment by john-shepherdson** [comment]
(sent on 25/05/2023)

Tomas,

I will add the details to our test instance of CDC so we can harvest your records over the weekend.
In the meantime, I notice there is one valid and one invalid ([sample@test.com](mailto:sample@test.com))admin email address returned by the Identify verb (not a problem at our end).

Also, here are the results of the BASE validation (http://oval.base-search.net/), for your information.

**Comment by john-shepherdson** [comment]
Tomas,

We did a test harvest over the weekend and got 7 records.
As per the OVAL results in my previous email, incremental harvesting in not supported by your endpoint (see the error messages about from and until dates used with the ListRecords verb). This means that any changes (editing or removing existing records, adding new records) will not be picked up by the daily incremental CDC harvesting runs, but will be seen by the full harvest on Sundays.

Regards,

John

**Comment by MortenSikt** [comment]
Will these records first be visible in the catalogue after the re-harvesting run on Sunday?

**Comment by john-shepherdson** [comment]
I expect them (7) to be in the UI

**Comment by KristinaS4** [comment]
We cannot find them in CDC, however they are available in the staging version of CDC.
