### ISSUE TITLE
Update Changelogs for v 3.3.0

### ISSUE THREAD

**Issue by john-shepherdson** [cessda/cessda.cdc.versions#551]
```[tasklist]
### Tasks
- [x] Metadata Harvester
- [x] Metadata Validator
```

**Comment by matthew-morris-cessda** [comment]
https://github.com/cessda/cessda.metadata.harvester/commit/8c6d07d1f14b7bd57ce24782a6936297867617bc

**Comment by matthew-morris-cessda** [comment]
https://github.com/cessda/cessda.cmv.console/commit/f3212b312001bd060627009bfefe8dbd33bc8f7a

**Comment by matthew-morris-cessda** [comment]
All changelogs updated

**Comment by matthew-morris-cessda** [comment]
DOIs have been added to the harvester and the validator
