### ISSUE TITLE
SiteMapper Misbehaviour

### ISSUE THREAD

**Issue by kpapag** [cessda/cessda.cdc.versions#554]
this was noticed during FUJI FAIR assessment script which uses CDC sitemap for gathering studies URL's

![Screenshot_0](https://github.com/cessda/cessda.cdc.versions/assets/12574598/c35dff6d-317a-4888-98ac-d83c50fb4e54)

![Screenshot_1](https://github.com/cessda/cessda.cdc.versions/assets/12574598/643ceed9-e9a0-468e-83e2-0b44c931b5ad)

![Screenshot_2](https://github.com/cessda/cessda.cdc.versions/assets/12574598/a1f759d6-922a-485c-9ae5-a6fd051b3f30)

**Comment by matthew-morris-cessda** [comment]
The count of 47,405 is as expected because this reflects the amount of records *without language deduplication* present in Elasticsearch. The counts on the CDC user interface are deduplicated so studies in many languages don't show up twice, inflating the numbers.
