### ISSUE TITLE
Not all Topic Classifications in SearchAPI documentation are presented

### ISSUE THREAD

**Issue by kpapag** [cessda/cessda.cdc.versions#555]
Topic Classifications presented in CDC SearchAPI documentation are currently hard coded and not system generated, which results in only a few options available for testing the API.

![Screenshot_1](https://github.com/cessda/cessda.cdc.versions/assets/12574598/31139ed3-9298-4df0-bedb-63e474b49d54)

**Comment by john-shepherdson** [comment]
Check if fixed
