### ISSUE TITLE
"keywords" search term misbehave when included in API call

### ISSUE THREAD

**Issue by kpapag** [cessda/cessda.cdc.versions#556]
examples:

`"SearchTerms": {
        "metadataLanguage": "en",
        "limit": "200",
        "keywords": "covid"
    },
    "ResultsCount": {
        "from": 0,
        "to": 200,
        "retrieved": 200,
        "available": 379
    }`

`"SearchTerms": {
        "metadataLanguage": "en",
        "limit": "200",
        "keywords": "COVID"
    },
    "ResultsCount": {
        "from": 0,
        "to": 0,
        "retrieved": 0,
        "available": 0
    }`

`"SearchTerms": {
        "metadataLanguage": "en",
        "limit": "200",
        "keywords": "covid-19"
    },
    "ResultsCount": {
        "from": 0,
        "to": 0,
        "retrieved": 0,
        "available": 0
    }`

**Comment by john-shepherdson** [comment]
Check if this is fixed

**Comment by matthew-morris-cessda** [comment]
Fixed in https://github.com/cessda/cessda.cdc.searchkit/pull/147
