### ISSUE TITLE
Explore possibility to add information on data access

### ISSUE THREAD

**Issue by MortenSikt** [cessda/cessda.cdc.versions#557]
With the new profiles, data access structure is enhanced. Two tasks:

1. Explore profiles for possibilities to harvest information
2. Determine if any SP have populated relevant information for testing functionality

See also https://github.com/cessda/cessda.cdc.versions/issues/361

**Comment by MortenSikt** [comment]
For this to be a possibility, metadata needs to contain information as specified in https://doi.org/10.5281/zenodo.5554488 

Reviewing the profiles

Updated 2.5: Does not contain the required elements

3.2 profile: Does not contain the required elements

**Comment by MortenSikt** [comment]
As this does not exist in the profile there are 2 options

1) Add information from updated access conditions to the profiles, validity of information needs to be checked

2) Do a mapping of SPs access conditions to the CV planned

There are advantages and disadvantages to both.

1) Is the most "correct" way, but it requires the implementation of a new metadata element from SPs. 

2) Seems the faster, but least interoperable way. It would be a more complicated procedure than what is done for Publisher mapping. 

option 2 is probably not feasible

Question then remains if I can just add the suggested profile information to 2.5 and 3.2/3 profiles and we can test. But it is very doubtful that any SP has this information in their metadata yet, so there is not much to test this against.

**Comment by MortenSikt** [comment]
https://github.com/cessda/cessda.metadata.profiles/issues/104

**Comment by MortenSikt** [comment]
DDI 2.5: https://github.com/cessda/cessda.metadata.profiles/blob/fe51d83c1217f6d04021d2054963b3f4648a094b/CDC_2.5_PROFILE/cdc25_profile.xml#L1206
DDI 2.6: https://github.com/cessda/cessda.metadata.profiles/blob/fe51d83c1217f6d04021d2054963b3f4648a094b/CDC_2.6_PROFILE/cdc26_profile.xml#L1166
DDI 3.2: https://github.com/cessda/cessda.metadata.profiles/blob/fe51d83c1217f6d04021d2054963b3f4648a094b/CDC_3.2_PROFILE/cdc32_profile.xml#L1272
DDI 3.3: https://github.com/cessda/cessda.metadata.profiles/blob/fe51d83c1217f6d04021d2054963b3f4648a094b/CDC_3.3_PROFILE/cdc33_profile.xml#L1272

**Comment by MortenSikt** [comment]
In reviewing access conditions for SPs we are unable to locate any actionable information on access conditions in the OAI-PMH endpoints from SPs using Dataverse. But in reviewing the metadata export from these Dataverse instances, we see that the information is available in the JSON and OAI_ORE exports. The information is located at a file level with information on Restricted: true OR false. Two examples below.

We are wondering if this information is ingested in the CDC in any way so that we can use it? @john-shepherdson @matthew-morris-cessda  

SciensesPo: 

- SP catalogue: https://doi.org/10.21410/7E4/TSQKNX  
- CDC: https://datacatalogue.cessda.eu/detail?lang=fr&q=eeda6d03fc6a791121622d9223cad2cb4b02fdf06b49991e4119840353ab8040 
- JSON from Dataverse: https://data.sciencespo.fr/api/datasets/export?exporter=dataverse_json&persistentId=doi%3A10.21410/7E4/TSQKNX

SoDaNet: 

- SP catalogue: https://doi.org/10.17903/FK2/GBISOH 
- CDC: https://datacatalogue.cessda.eu/detail?lang=en&q=8b04afa1800559e75546303433cab4f130f1dac48253d95a56cffc4344f5fc19
- JSON from Dataverse: https://datacatalogue.sodanet.gr/api/datasets/export?exporter=dataverse_json&persistentId=doi%3A10.17903/FK2/GBISOH

**Comment by john-shepherdson** [comment]
For the SciencesPo case, the Dataverse Json gives this level of detail per associated file:
via https://doi.org/10.21410/7E4/TSQKNX

`{
"label":"cdsp_meta_electoral_surveys.xlsx",
"restricted":false,
"version":1,
"datasetVersionId":3280,
"categories":[
"Documentation",
],
"dataFile":{
"id":5071,
"persistentId":"",
"pidURL":"",
"filename":"cdsp_meta_electoral_surveys.xlsx",
"contentType":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
"filesize":591119,
"categories":[
"Documentation",
],
"storageIdentifier":"file://18708dc65d4-13cba4f17d0f",
"rootDataFileId":-1,
"md5":"11c833dbb915c655a7adef77f2b52216",
"checksum":{
"type":"MD5",
"value":"11c833dbb915c655a7adef77f2b52216",
},
"creationDate":"2023-03-22",`

But for the same file in the same study their Dataverse OAI-PMH endpoint gives us this, 
via https://data.sciencespo.fr/oai?verb=GetRecord&identifier=doi%3A10.21410/7E4/TSQKNX&metadataPrefix=oai_ddi

`<otherMat ID="f5071" URI="https://data.sciencespo.fr/api/access/datafile/5071" level="datafile">
<labl>cdsp_meta_electoral_surveys.xlsx</labl>
<txt/>
<notes level="file" type="DATAVERSE:CONTENTTYPE" subject="Content/MIME Type">application/vnd.openxmlformats-officedocument.spreadsheetml.sheet</notes>
</otherMat>`

**Comment by john-shepherdson** [comment]
Same for the SoDaN et example (via their OAI-PMH endpoint):

`<otherMat ID="f6005" URI="https://datacatalogue.sodanet.gr/api/access/datafile/6005" level="datafile">
<labl>Humanitarian assistance and social protection in Greece - Annex.pdf</labl>
<notes level="file" type="DATAVERSE:CONTENTTYPE" subject="Content/MIME Type">application/pdf</notes>
</otherMat>`

So it appears that CDC does not receive the required information from Dataverse OAI-PMH endpoints

**Comment by MortenSikt** [comment]
In the UG meeting today Ricarda (DANS) mentioned that Datacite recieves aggregated information on access information for the record:

>  Dear Morten,
> 
> I checked with my colleague on how Dataverse classifies datasets as open or restricted and he explained the following to me.
> 
> In Dataverse, the licence is set at dataset level but files are individually set to be open or restricted.
> You can therefore have a dataset that has some open and some restricted files.
> 
> In the Dataverse interface there is no indication of open/restricted at the dataset level.
> However, Dataverse adds this information to before the harvest in the OAI-PMH interface. The rule is that if there is one or more restricted files the dataset is restricted, if all files are open it is open.
> 
> In the OAI endpoint this is then indicated with:
> rightsList 
> rights rightsURI="info:eu-repo/semantics/restrictedAccess"
> 
> or
> rightsList 
> rights rightsURI="info:eu-repo/semantics/openAccess"/>
> 
> You can view this here:
> https://ssh.datastations.nl/oai?verb=ListRecords&metadataPrefix=oai_datacite&set=social_sciences
> 
> This does thus mean that Dataverse makes information available about the access of a dataset on dataset-level in the OAI-endpoint.
> 
> I don’t know whether and how this could be added into the DDI output.
> Hopefully this information is useful for you.

So the question then becomes can we change the OAI endpoint from OAI_DDI to OAI_Datacite, perhaps just for this information?

I checked other SPs in catalogue, and information is also present there under rights list:

Sodha: https://www.sodha.be/oai?verb=GetRecord&identifier=doi%3A10.34934%2FDVN%2FDDH1FW&metadataPrefix=oai_datacite

SciencesPo: https://data.sciencespo.fr/oai?verb=GetRecord&identifier=doi%3A10.21410%2F7E4%2FTSQKNX&metadataPrefix=oai_datacite

AUSSDA: https://data.aussda.at/oai?verb=GetRecord&identifier=doi%3A10.11587%2FPWNMRM&metadataPrefix=oai_datacite

SoDaNet: https://datacatalogue.sodanet.gr/oai?verb=GetRecord&identifier=doi%3A10.17903%2FFK2%2FCE0VSD&metadataPrefix=oai_datacite

all endpoints have information located as per Ricarda's specification

**Comment by john-shepherdson** [comment]
It is just a matter of configuration to change the metadata prefix. So yes, it can be done.
Are there any other differences between the same record harvested using the oai_ddi and oai_datacite metadata prefixes?

**Comment by matthew-morris-cessda** [comment]
Unfortunatly the `oai_datacite` representation doesn't represent as much information as `oai_ddi` (i.e. DDI 2.5). We also don't have a DataCite parser at the moment.

**Comment by KristinaS4** [comment]
In the User Group is was agreed that:

- The data access information should be displayed above the Abstract section on the detailed study pages.
- The field should be called 'Data access'.
- If no information on data access exists, the text should be 'Information not available' and not 'Not available' as is now used for the other fields as this could indicate that the data itself is not available.

**Comment by matthew-morris-cessda** [comment]
@markusjt Are there any FSD examples?

**Comment by markusjt** [comment]
> @markusjt Are there any FSD examples?

Example of open access (we call it A): https://services.fsd.tuni.fi/v0/oai?verb=GetRecord&metadataPrefix=oai_ddi25&identifier=oai:fsd.uta.fi:FSD3896
Everything else would fall into restricted access. Full list of data access levels we use:
```xml
<restrctn xml:lang="fi" >Aineisto on (A) vapaasti käytettävissä ilman rekisteröitymistä (CC BY 4.0).</restrctn>
<restrctn xml:lang="en" >The dataset is (A) openly available for all users without registration (CC BY 4.0).</restrctn> 
```
```xml
<restrctn xml:lang="fi" >Aineisto on käytettävissä (B) tutkimukseen, opetukseen ja opiskeluun.</restrctn>
<restrctn xml:lang="en" >The dataset is (B) available for research, teaching and study.</restrctn> 
```
```xml
<restrctn xml:lang="fi" >Aineisto on käytettävissä (C) vain tutkimukseen ja ylempiin opinnäytteisiin.</restrctn>
<restrctn xml:lang="en" >The dataset is (C) available only for research including master's theses.</restrctn> 
```
```xml
<restrctn xml:lang="fi" >Aineisto on käytettävissä (D) vain luovuttajan luvalla.</restrctn>
<restrctn xml:lang="en" >The dataset is (D) available only by permission from the data depositor/creator.</restrctn> 
```

**Comment by MortenSikt** [comment]
Attached is an overview of confirmed access conditions mapping from SPs. We are in discussions with FORS and GESIS about their access conditions as they had some comments to the mappings we had done. If this is not resolved before the 3.7 release, we can include them later on

[SPs access conditions mapping.xlsx](https://github.com/user-attachments/files/16172982/SPs.access.conditions.mapping.xlsx)

**Comment by MortenSikt** [comment]
Had a call with Marielle Kappeler from FORS on the information they provide.

In order to do a correct mapping of their access conditions we need information that they hold about the study/dataset license. This information is not provided in the OAI-PMH endpoint. FORS will discuss if this is something they can provide.

In the call we discussed that the current information we receive might be misguiding (since it lacks the crucial information from license). I am therefor curious if it is possible to omit this information from what we are presenting from studies from FORS?

**Comment by MortenSikt** [comment]
Add functionality for the 4 SPs with the mapping. 

I am curious if it is possible to add support for harvesting code values from 2.6 and 3.3 even though we do not have any valid example data for this

**Comment by markusjt** [comment]
@MortenSikt One answer and two questions below.

> I am curious if it is possible to add support for harvesting code values from 2.6 and 3.3 even though we do not have any valid example data for this

We don't currently have harvesting support for 2.6 so that will have to wait but I can probably add for 3.3 already.

Quoted from @KristinaS4 earlier in this issue:
> If no information on data access exists, the text should be 'Information not available' and not 'Not available' as is now used for the other fields as this could indicate that the data itself is not available.

Should this 'Information not available' also be translated to all supported languages similar to how 'Not available' is currently being translated? E.g. Finnish metadata has 'Ei tiedossa' for 'Not available' so this  'Information not available' would be 'Tietoa ei ole saatavilla'.

> The information should be displayed in the search results as well

Any ideas where it would be displayed or do I just try something and see what looks good?

**Comment by MortenSikt** [comment]
Yes we need it translated to all the languages, here are for the other languages:

    Czech: Informace nejsou k dispozici
    Danish: Information er ikke tilgængelig
    Dutch: Informatie niet beschikbaar
    French: Information non disponible
    German: Informationen nicht verfügbar
    Greek: Οι πληροφορίες δεν είναι διαθέσιμες
    Slovakian: Informácie nie sú k dispozícii
    Slovenian: Informacije niso na voljo
    Swedish: Information är inte tillgänglig

With regards for display, I am perhaps thinking the bottom information page:

![Access](https://github.com/user-attachments/assets/a3194805-17cc-41cb-921d-9fdc3e9a122a)

With a box for with "Data access: Open/Restricted", I do not think it is a good idea to display "information not available" here for those that we do not have information from.

**Comment by markusjt** [comment]
Thanks! I'll see how it fits in there. I can also add Norwegian translation since the translation file exists already. Now I'm actually wondering why we haven't added Norwegian back as an option for language select.

**Comment by markusjt** [comment]
@MortenSikt What do you think about having data access between languages and access study button, and with a lock icon that changes depending if it's open or restricted:
![dataaccess](https://github.com/user-attachments/assets/28923c52-b78e-4b67-8a08-aae0517efd6c)

Also, should I add Norwegian to the [list of languages](https://github.com/cessda/cessda.cdc.searchkit/blob/main/src/utilities/language.ts) or was there some reason why it hasn't been added yet? After adding it on my dev server I can see that Sikt has even more metadata in Norwegian than in English. Then I'll also need a translation for "Information not available" in Norwegian and maybe also in Portuguese even though it's not enabled but there is a translation file for it already.

**Comment by MortenSikt** [comment]
I think it looks good with that position, and the lock icon is a nice touch!

With regards to Norwegian, if I recall correctly the language was removed since there are alot of errors in the metadata from Sikt. The metadata from Sikt is a copy of our old Nesstar system (which was replaced almost 3 years ago) and we do not have control over those metadata . Probably should remove our records from CDC to be honest, but that is another issue.

As for portuguese, I do not know why it is not present. But I think we should leave it excluded as well for now, might be a reason for it.

**Comment by markusjt** [comment]
> I think it looks good with that position, and the lock icon is a nice touch!
> 
> With regards to Norwegian, if I recall correctly the language was removed since there are alot of errors in the metadata from Sikt. The metadata from Sikt is a copy of our old Nesstar system (which was replaced almost 3 years ago) and we do not have control over those metadata . Probably should remove our records from CDC to be honest, but that is another issue.
> 
> As for portuguese, I do not know why it is not present. But I think we should leave it excluded as well for now, might be a reason for it.

Makes sense, thanks! I can still add the translations already if you can provide them also.

**Comment by MortenSikt** [comment]
Portuguese: Informação não disponível
    Norwegian: Informasjon er ikke tilgjengelig
