### ISSUE TITLE
Add series information to the study records in CDC

### ISSUE THREAD

**Issue by MortenSikt** [cessda/cessda.cdc.versions#559]
Many SPs have long running series of data that often see more use than single-round studies. Information on this is limited in the CDC, some are included through Similar results (see also https://github.com/cessda/cessda.cdc.versions/issues/288). But this does not give a good overview.

The CDC profile does not include the relevant elements for series, but these exist within the EQB profiles. Those relevant would be Title and a URL to an information page on SPs website. If it is possible to use the EQB profiles, following elements could be used:

```
<pr:Used xpath="/codeBook/stdyDscr/citation/serStmt/serName" isRequired="false">
<r:Description>
<r:Content>Required: Optional</r:Content>
<r:Content>ElementType: Content element</r:Content>
<r:Content>ElementRepeatable: Yes</r:Content>
<r:Content>Usage: A title or name for the study group.</r:Content>
<r:Content>EQB_ID_Element: 7.3/studyGroupTitle</r:Content>
<r:Content>EQB_UI_Label: Filter/Part of study group/series.</r:Content>
</r:Description>
<pr:Instructions>
<r:Content>
<Constraints><OptionalNodeConstraint/></Constraints>
</r:Content>
</pr:Instructions>
</pr:Used>
<pr:Used xpath="/codeBook/stdyDscr/citation/serStmt/serName/@xml:lang" isRequired="false">
<r:Description>
<r:Content>
Required: Mandatory if '..serStmt/serName' element is present.
</r:Content>
<r:Content>ElementType: Attribute</r:Content>
<r:Content>EQB_ID_Element: 7.3.1/studyGroupTitleLang</r:Content>
<r:Content>EQB_UI_Label: not displayed (internal info).</r:Content>
</r:Description>
<pr:Instructions>
<r:Content>
<Constraints><MandatoryNodeIfParentPresentConstraint/></Constraints>
</r:Content>
</pr:Instructions>
</pr:Used>
<pr:Used xpath="/codeBook/stdyDscr/citation/serStmt/serInfo/ExtLink" isRequired="false">
<r:Description>
<r:Content>Required: Optional</r:Content>
<r:Content>ElementType: Content element</r:Content>
<r:Content>ElementRepeatable: Yes</r:Content>
<r:Content>
Usage: A value of a persistent identifier for the study group.
</r:Content>
<r:Content>EQB_ID_Element: 7.2/studyGroupID</r:Content>
<r:Content>EQB_UI_Label: not displayed (internal info).</r:Content>
</r:Description>
<pr:Instructions>
<r:Content>
<Constraints><OptionalNodeConstraint/></Constraints>
</r:Content>
</pr:Instructions>
</pr:Used>
<pr:Used xpath="/codeBook/stdyDscr/citation/serStmt/serInfo/ExtLink/@URI" isRequired="false">
<r:Description>
<r:Content>
Required: Mandatory if ',,serInfo/ExtLink' element is present.
</r:Content>
<r:Content>ElementType: Attribute</r:Content>
<r:Content>
Usage: An URL or URN (a reference to a web resource that specifies its location) linking to the study group.
</r:Content>
<r:Content>EQB_ID_Element: 7.4/studyGroupUrl</r:Content>
<r:Content>EQB_UI_Label: included as hyperlink</r:Content>
</r:Description>
<pr:Instructions>
<r:Content>
<Constraints><MandatoryNodeIfParentPresentConstraint/></Constraints>
</r:Content>
</pr:Instructions>
</pr:Used>
```

**Comment by MortenSikt** [comment]
**AUSSDA** 
study from series: https://datacatalogue.cessda.eu/detail?lang=en&q=3fc5e709f7ac8880679d47323f7c2360b8b1cb6782d17e4e502a8a2c27eb68d9 

DDI-C: `serStmt/serName & serInfo`

**DASSI**
study from series: https://datacatalogue.cessda.eu/detail?lang=en&q=ab5f7b96a8a00b9bb33aaee034b289f62062d137fc6a2406fba8b1d1f28c9043

DDI-C: `serStmt@URI, / serName & serInfo`


**FSD**
study from series: https://datacatalogue.cessda.eu/detail?lang=en&q=065d1819bff2962697eab6dd7e21cc8a12e7aaa7b32cb4ec694bef219864a801 

DDI-C `serStmt@URI, /serName & serInfo`

**SASD**
study from series: https://datacatalogue.cessda.eu/detail?lang=en&q=a1136a1830ab656649ae9f4ebcc344e2ca0898fc361300064aee414ab6404a70

DDI-C: `serStmt/serName & serInfo` 

**ADP**
study from series: https://datacatalogue.cessda.eu/detail?lang=en&q=c87599ae997e569e033f30f32387695ba13f02b0ca5e265e494eb8217f032a10

getting errors on oai, but SP site shows information: https://www.adp.fdv.uni-lj.si/opisi/ads002/

**SoDaNet**
study from series: https://datacatalogue.cessda.eu/detail?lang=en&q=30f29e38fccb0afe43cccfdae48493db4e6cece7a9d14f794883ab4b307b87d8

DDI-C `serStmt/serName`

**SODHA**
study from series: https://datacatalogue.cessda.eu/detail?lang=en&q=ad88e92e363e0225699604083c3acda3ba28d07eb693d6951e3201abf1ca39ee

DDI-C `serStmt/serName & serInfo`

**SND**
study from series: https://datacatalogue.cessda.eu/detail?lang=en&q=5c82ead1b187a50b43070fdb2526a22dfeb6295ca72655e08803fccfa8e72151

Unable to access oai, but SPs landing page has information but its not present in their own xml export on page

**UKDS**
study from series: https://datacatalogue.cessda.eu/detail?lang=en&q=67972e855a332c809ee79b02482273b456eb9642a7dccb2f7a83e77a538f38a5

some series info is located in `stdyDscr/citation/titlStmt/subTitl & altTitl`

**Comment by MortenSikt** [comment]
From CMM v3 relevant elements are

10.3 - Study Group Name
10.3.1 - Language of Study Group Name
10.4 - Study Group Description
10.4.1 - Language of Study Group Description
10.4.2 - Study Group Description URI

Apart from UKDS and SND, 6 SPs who have series information use 10.3 `serName` , 5 also use `serInfo` and 2 use @uri aswell.

This information goes beyond related studies, and if possible should be displayed in the catalogue

**Comment by KristinaS4** [comment]
In the User Group (29.05.2024) the following was decided:

Series information will be placed after the study number and before the abstract in the Summary Information section
UI labels:
serStmt/@URI → Label not needed (this link is attached to name of the series)
serStmt/serName (name of the series) → Series
serStmt/serInfo (description of the series) → Series

The series description will have a cut-off at 600 characters (with spaces) similar to the cut-off for long abstracts, with a 'Read more' button.
