### ISSUE TITLE
Add funding information for records in the CDC

### ISSUE THREAD

**Issue by MortenSikt** [cessda/cessda.cdc.versions#560]
Information on the funders of the study is relevant for expore and attribution of the institutions paying for the collection of the research data. This information should be added to the CDC.

Unsure if this is possible without addition to the profiles, since the relevant elements does not exist within the CDC nor the EQB profiles.

**Comment by MortenSikt** [comment]
Relevant elements is specified in CMM version 3 for fields

1.1.6.1 - Funding agency reference
1.1.6.1.1 - Type of Funding Agency Reference (for DDI-L)
1.1.6.2 - Grant Number
1.1.6.3 - Grant Title
1.1.6.4 - Funder Role

Elements 1.1.6.1.1 is only relevant for DDI-L, 1.1.6.4 is set as Optional. 1.1.6.3 is not available in DDI-C

Primary initial support should be for 1.1.6.1 & 1.1.6.2

**Comment by MortenSikt** [comment]
Study with correct DDI-C 2.5 structure: https://datacatalogue.cessda.eu/detail?lang=en&q=183b8fd6f3c7ce851de590d408b44e7ea718cf96837cebcc72d4f17f4b1c23d4

**Comment by matthew-morris-cessda** [comment]
Funding information is now parsed into the CDC model and is indexed into Elasticsearch

**Comment by KristinaS4** [comment]
In the User Group (29.05.2024) the following was decided:
Add a new section (c.f. Methodology) between Data Collection Mode and Access

UI labels:
Title of the section: Funding information
Display all of the following that are present in the metadata (do not include if value is not available)
grantNo/@agency → Funder
grantNo → Grant Number
grantNo/@role → TBD (I will see if any SP use this field and what they call it before we decide on the UI label)

Regarding the profile: name of the funder (grantNo/@agency) to be mandatory if there is information in the grantNo field

**Comment by markusjt** [comment]
@KristinaS4 @MortenSikt I could use some clarifications:

1. Should this new section be shown even when there's no funding information? Currently I've hidden it if there's nothing but the other option is to add the section title and some text below it, e.g. "Not available" (just adding section title without adding anything below it would look bad, I checked).

1. Should anything be added to JSON-LD? I see funder in https://developers.google.com/search/docs/appearance/structured-data/dataset but I don't see where grant number would go.

**Comment by KristinaS4** [comment]
@markusjt 
1. We discussed in the User Group that the field should be hidden if there is no information rather than having 'Not available', so what you have done is good.
2. I am not really that familiar with JSON-LD. Can you add funder but not grant number? I don't see a field for grant number either.
 
It looks good in the test instance so I think you can close this issue (again).

**Comment by markusjt** [comment]
Thank you @KristinaS4 !
> I am not really that familiar with JSON-LD. Can you add funder but not grant number? I don't see a field for grant number either.

We could add just the funders but I just realized that currently we don't actually have the information whether it's a person or organization and that seems to be mandatory.

When searching about adding grant numbers, I found a somewhat recent (from Feb) [related issue on Dataverse's issue tracker](https://github.com/IQSS/dataverse/issues/10296). It seems other people are also thinking on how to show grant numbers but haven't really tested yet how Google's validation tools would respond when following e.g. [Science on schema.org guidelines](https://github.com/ESIPFed/science-on-schema.org/blob/master/guides/Dataset.md#funding).

Maybe it's better to leave funding information out of JSON-LD for now unless we decide on some format we want to try for grant numbers or we add just funders with the assumption that they are organizations (most of them are but not all).

**Comment by matthew-morris-cessda** [comment]
FSD would like the funder to be parsed even if a grant number is not present

**Comment by KristinaS4** [comment]
Here is an example of a study with funders, but no grant numbers: https://datacatalogue.cessda.eu/detail?lang=en&q=9153705deb0a6655a23d882fd8946cf8f07e32ea3a2d947fefef4be9017406db

**Comment by markusjt** [comment]
> Here is an example of a study with funders, but no grant numbers: https://datacatalogue.cessda.eu/detail?lang=en&q=9153705deb0a6655a23d882fd8946cf8f07e32ea3a2d947fefef4be9017406db

Same study in FSD's OAI-PMH endpoint: https://services.fsd.tuni.fi/v0/oai?verb=GetRecord&metadataPrefix=oai_ddi25&identifier=oai:fsd.uta.fi:FSD3819

CDC Searchkit will also require changes after indexing has been changed. Currently UI assumes that grant number will be there if any funding information is available.
