### ISSUE TITLE
Update SND endpoint due to restructuring of the SND catalogue

### ISSUE THREAD

**Issue by matthew-morris-cessda** [cessda/cessda.cdc.versions#564]
The MO IT team recieved an email from SND about changes to their OAI-PMH endpoint.

> Hi!
> We just launched a major restructuring of the SND-catalogue and this will have effects on out OAI-PMH provider.
> The datasets was previously grouped under a study and now they a represented as standalone datasets with versions.
> The identifiers for the sets are also changed to use the standard identifier with a type prefix eg:
> <https://snd.gu.se/oai-pmh?verb=ListRecords&metadataPrefix=ddi25&set=subject:ssif:5> (all datasets categorized under Social Science if the swedish version of Field of Research and Development).
> So you might have to change the configuration for the harvester.
> 
> We are also curently rebuilding the metadata exports so we will get more fields into DDI 2.5 and do a complete rewrite of the DDI-L export.
> 
> Best regards,
> Olof

This will require the following changes

- Endpoint URL: `https://snd.gu.se/en/oai-pmh` → `https://snd.gu.se/oai-pmh`
- `setSpec`: `subject:social-sciences` → `subject:ssif:5`

**Comment by john-shepherdson** [comment]
BASE validation results (http://oval.base-search.net/)

<img width="637" alt="Screenshot 2023-06-15 at 10 34 54" src="https://github.com/cessda/cessda.cdc.versions/assets/107628491/289d2848-7ecc-4070-9b4b-a902e4ac667b">

**Comment by matthew-morris-cessda** [comment]
Looks like an error to me, given that the failing setSpec is `principal:` and there aren't any instances of `principal:` on it's own in the OAI response.

**Comment by matthew-morris-cessda** [comment]
On further investigation, this is reproducible in the OAI-PMH endpoint with a `ListRecords` request. For `2023-101-1`.

```xml
...
    <record>
      <header>
  <identifier>2023-101-1</identifier>
  <datestamp>2023-05-24T06:51:22Z</datestamp>
  <setSpec>principal:</setSpec>
  <setSpec>subject:cessda:Politics.Elections</setSpec>
  <setSpec>subject:cessda:Politics.PoliticalBehaviourAndAttitudes</setSpec>
  <setSpec>subject:ssif:5</setSpec>
  <setSpec>subject:ssif:506</setSpec>
  <setSpec>subject:cessda:Politics</setSpec>
</header>
...
```

Note for the first `setSpec` that `principal:` is present.

**Comment by borsna** [comment]
Ah, got it. was looking on the set listing. this is an error where domain is missing for this principal. will do a fix and push it so principal sets are genererated in the correct way

**Comment by matthew-morris-cessda** [comment]
See https://snd.gu.se/oai-pmh?verb=GetRecord&metadataPrefix=oai_dc&identifier=2023-69-1

**Comment by borsna** [comment]
@matthew-morris-cessda fixed the `principal:` sets now. A principal setSpec should not be generated if the domain for the principal is set in for the dataset.

**Comment by matthew-morris-cessda** [comment]
Confirmed fixed

![image](https://github.com/cessda/cessda.cdc.versions/assets/68543725/bec92df0-583e-49f2-9d4b-d03fc2dad33e)

**Comment by john-shepherdson** [comment]
See https://github.com/cessda/cessda.metadata.harvester/pull/22

**Comment by john-shepherdson** [comment]
1,316 records harvested. 0 XML schema violations, 0 constrain violations.
