### ISSUE TITLE
Remove "unwrapped" records from being harvested

### ISSUE THREAD

**Issue by matthew-morris-cessda** [cessda/cessda.cdc.versions#565]
These were initially required by the Metadata Validator, but since https://github.com/cessda/cessda.cmv.core/issues/80 has been resolved this can be removed.

The `wrapped` directory should be renamed to something like `source`.

**Comment by john-shepherdson** [comment]
Please add before and after values for time taken to complete a full harvest and memory usage, to confirm the prediction that that both will be reduced by these changes

**Comment by matthew-morris-cessda** [comment]
Before: 1:51 (from 02:03 to 03:54)
After: 1:05 (from 14:47 to 15:52)

This is a reduction of approximately 45 minutes.
