### ISSUE TITLE
User is interested in finding all studies for a specific language based on a free text search, for instance “réseaux sociaux“

### ISSUE THREAD

**Issue by KristinaS4** [cessda/cessda.cdc.versions#587]
**As a user I am interested in finding all studies for a specific language based on a free text search**

1. I use the language selection functionality next to the search box:

![image](https://github.com/cessda/cessda.cdc.versions/assets/112862817/abc0cb1b-9a76-4a9c-88ab-6eacefa4d7a9)

2. In the search box I input my specific search term:

![image](https://github.com/cessda/cessda.cdc.versions/assets/112862817/ab0ca49a-24ee-476b-966c-925640005045)

3. I am expecting information on amount of results for the specified language and search term:

![image](https://github.com/cessda/cessda.cdc.versions/assets/112862817/4771fbfd-4135-4bc0-9b15-54b3f231d26a)

4. I want to use the navigator to look through the pages

![image](https://github.com/cessda/cessda.cdc.versions/assets/116061162/1ce96c84-ea2d-41be-a145-8ac94bc7ccec)

5. I also want to edit the amount of results shown in a page

![image](https://github.com/cessda/cessda.cdc.versions/assets/116061162/279d6589-c6b6-4d6d-bbe2-df1c7968d50f)

**Comment by toni-sissala** [comment]
I have created selenium tests that make sure the navigator and results per page selections work as expected in one case. I have not repeated the same tests (change page and number of results) for each of these cases similar as there are in these user stories.

In this user story the search terms only return 14 results (picture in step 3), so the user cannot navigate to a second page, unless he/she first changes the results per page to 10.
