### ISSUE TITLE
Update Changelogs for v 3.4.0

### ISSUE THREAD

**Issue by john-shepherdson** [cessda/cessda.cdc.versions#603]
- [x] Searchkit - 10.5281/zenodo.8277027
- [x] Harvester - 10.5281/zenodo.8277067
- [x] Indexer - 10.5281/zenodo.8277076
- [x] CMV Console - 10.5281/zenodo.8277085
- [x] https://github.com/cessda/cessda.cdc.aggregator.oai-pmh-repo-handler/issues/51

**Comment by matthew-morris-cessda** [comment]
All components apart from the OAI-PMH repo handler now have updated changelogs

**Comment by toni-sissala** [comment]
Updated changelog for OAI-PMH Repo Handler is ready for review at https://github.com/cessda/cessda.cdc.aggregator.oai-pmh-repo-handler/pull/52
