### ISSUE TITLE
FORS duplicate records

### ISSUE THREAD

**Issue by john-shepherdson** [cessda/cessda.cdc.versions#612]
Thu, 21 Sept 2023 at 13:25, Brian Kleiner wrote:

John

I was informed that in the CDC there are multiple versions of the same datasets harvested from FORS/SWISSUbase. This is apparently because we have metadata for the same datasets in multiple languages in some cases. Is there any way to change this so that there is only one version per dataset, e.g., by using the DOI?

Best,

Brian

**Comment by john-shepherdson** [comment]
Brian,

I will file an issue and hopefully we will address this next week and get back to you soon.

John

**Comment by matthew-morris-cessda** [comment]
Could examples of duplicate records be attached to this issue?

**Comment by matthew-morris-cessda** [comment]
The following search, https://datacatalogue.cessda.eu/?publisher.publisher[0]=FORS%20-%20Swiss%20Centre%20of%20Expertise%20in%20the%20Social%20Sciences&sort=title-ascending, doesn't appear to show any duplicates.
