### ISSUE TITLE
Release 3.4.1

### ISSUE THREAD

**Issue by john-shepherdson** [cessda/cessda.cdc.versions#613]
Due date - see Milestone.

- [ ] Update release checklist (All): https://docs.google.com/spreadsheets/d/1en3boDxzgxzkiIltHoWKajnYCbNf8RlvVtphJ3W7R30/edit#gid=910273208
- [x] Create release report (John): https://docs.google.com/document/d/15v8bb31qZ2Z3ZWNdm6hf9vtFkhPO3mW9SHz4Uogv1NI/edit#heading=h.yma78xy87756
- [x] Check endpoint configurations and re-set/remove any test settings (DANS, So.Da.Net, others?) so that they do not get propagated to production (Matthew)
- [x] Update CHANGELOG (Matthew)
- [x] Any changes needed to User Guide? (Kristina)
- [x] Any changes needed to About text? (Kristina)

**Comment by KristinaS4** [comment]
We would need to update the About text to reflect that the latest version of CDC will be 3.4.1. There should be no need to change the User Guide.

**Comment by john-shepherdson** [comment]
Except that the User Guide says "This is the user guide for version 3.4.0 of the CESSDA Data Catalogue."
We have had discussions on and off about updating/not updating the version number in the UG/About pages for bug fix releases, as there is no difference to the user experience.

**Comment by KristinaS4** [comment]
That's true! We could just keep both as they are for now.

**Comment by john-shepherdson** [comment]
Will avoid doing work which adds no value. The CHANGELOG will record the bug fixes.

**Comment by matthew-morris-cessda** [comment]
All tickets closed

**Comment by john-shepherdson** [comment]
@KristinaS4 Please approve the release (the release checklist and report are ongoing and do not constitute blockers).

**Comment by matthew-morris-cessda** [comment]
CDC 3.4.1 has been released
