### ISSUE TITLE
Update CHANGELOG for 3.4.1

### ISSUE THREAD

**Issue by john-shepherdson** [cessda/cessda.cdc.versions#614]

**Comment by matthew-morris-cessda** [comment]
Changelogs have been updated for Searchkit and the OSMH Indexer

https://github.com/cessda/cessda.cdc.searchkit/commit/4730455c91b47dcd608e3008b1dc8d429b0c363f
https://github.com/cessda/cessda.cdc.osmh-indexer.cmm/commit/095445d6296b4fe46df31ea18faaf6c46db4aadb
