### ISSUE TITLE
Update About page for version 3.5.0

### ISSUE THREAD

**Issue by MortenSikt** [cessda/cessda.cdc.versions#634]
I have updated the about page for CDC located here: https://docs.google.com/document/d/1XzBC65fvuNqCNhctJgDicPKqNWh0DsPucVByly9kiU0/edit#heading=h.ia0ex66ykr5q

Changes are marked with yellow

**Comment by john-shepherdson** [comment]
This is a separate action to the User Guide updates, despite the required changes being detailed in the User Guide GDoc
