### ISSUE TITLE
BASE contains very few CDC records

### ISSUE THREAD

**Issue by john-shepherdson** [cessda/cessda.cdc.versions#637]
Specifying CDC as the content provider gives only 2 results

https://base-search.net/Search/Results?lookfor=cessda&type=all&sort=score%20desc,dctitle_sort%20asc&oaboost=1&refid=dcdden&filter[]=f_dccollection:ftcessda&l=en

Are most CDC records being rejected by the BASE aggregation process?

See also #525

**Comment by Joshocan** [comment]
[I will take this matter up. update will come soon ](https://www.base-search.net/Search/Results?type=all&lookfor=coll%3Aftcessda) --- this query  shows over 25,000 records

**Comment by john-shepherdson** [comment]
That is much better. Must be something wrong with the filter
