### ISSUE TITLE
Add ADP Kuha2 to list of harvestable endpoints

### ISSUE THREAD

**Issue by john-shepherdson** [cessda/cessda.cdc.versions#641]
From: Žibert, Gregor 
Date: Wed, 13 Mar 2024 at 15:34
Subject: Re: [CESSDA] ADP OAI-PMH endpoint
To: John Shepherdson

ADP has reestablished the Kuha2 OAI-PMH endpoint. Can you please check if everything is in order and include us again in the CESSDA Data Catalogue?

https://www.adp.fdv.uni-lj.si/v0/oai

**Comment by john-shepherdson** [comment]
Please add before the weekend so I can see the QA results in the staging dashboard next week

**Comment by matthew-morris-cessda** [comment]
ADP is being sucessfully harvested. Because we never changed ADP's configuration, this is working on production.

```json
{
  "insertId": "3i5blbmlncvp83bh",
  "jsonPayload": {
    "oai_record": "ADP",
    "oai_set": null,
    "level_value": 20000,
    "harvester_run_id": "2024-03-14T00:00:12.209461487Z",
    "@version": "1",
    "level": "INFO",
    "thread_name": "pool-2-thread-1",
    "logger_name": "eu.cessda.oaiharvester.Harvester",
    "message": "ADP: Set: null: Retrieved 579 records.",
    "@timestamp": "2024-03-14T00:03:27.648174101Z",
    "retrieved_records": 579
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      "pod_name": "cdc-agg-harvester-incremental-28506240-7hkvl",
      "namespace_name": "cdc-agg",
      "container_name": "harvester",
      "location": "europe-west1-b",
      "cluster_name": "production-cluster",
      "project_id": "cessda-prod"
    }
  },
  "timestamp": "2024-03-14T00:03:27.648976824Z",
  "severity": "INFO",
  "labels": {
    "k8s-pod/job-name": "cdc-agg-harvester-incremental-28506240",
    "compute.googleapis.com/resource_name": "gke-production-cluster-himem-pool-6d67c927-9w5c",
    "k8s-pod/controller-uid": "05bdde26-ed53-438a-a80a-765b7a9ac907"
  },
  "logName": "projects/cessda-prod/logs/stdout",
  "receiveTimestamp": "2024-03-14T00:03:28.931346902Z"
}
```

**Comment by matthew-morris-cessda** [comment]
ADP uses language tags in the form of `en-GB`. The current production version of the CDC indexer doesn't handle these correctly, but the latest version in staging does, as it ignores anything past the `-` character (e.g. `en-GB` becomes `en`).

**Comment by john-shepherdson** [comment]
**Email sent to ADP endpoint manager on 24/04/2024:**

Gregor,

It appears that ADP uses language tags of the form 'en-GB' whereas CDC is looking for the 'en' form.
As a result, your studies are not visible in the production instance of CDC, but can be seen in staging (as we have applied a fix there):
https://datacatalogue-staging.cessda.eu/?publisher.publisher[0]=Slovenian%20Social%20Science%20Data%20Archives%20%28ADP%29

So you can either wait until the next release of CDC (no date fixed) or change your metadata to use language tags that are compliant with ISO 639-1 (2 letter codes).

Regards,

John

**Comment by john-shepherdson** [comment]
Staging currently shows 267 records in Slovenian, 531 in English.
Production has 0 records in Slovenian, 531 in English.
