### ISSUE TITLE
Remove SoDaNet ARIA Dev Endpoint

### ISSUE THREAD

**Issue by john-shepherdson** [cessda/cessda.cdc.versions#643]
Do not propagate the configuration of this endpoint to production

**Comment by john-shepherdson** [comment]
![Screenshot 2024-03-27 at 15 24 26](https://github.com/cessda/cessda.cdc.versions/assets/107628491/c75a5ed1-9018-44aa-a927-f21046f5e8c7)

**Comment by matthew-morris-cessda** [comment]
SoDaNet test configuration has been removed as of https://github.com/cessda/cessda.cdc.aggregator.deploy/commit/26ec8419772ed7321356d8aefd76853080981925. I've removed the source XMLs from the Aggregator dev storage bucket as well.
