### ISSUE TITLE
Clone FSD COORDINATE repo to cessda GitHub

### ISSUE THREAD

**Issue by john-shepherdson** [cessda/cessda.cdc.versions#647]
- [x] Clone repo
- [x] Add standard non-functional files (as required by SQAaaS)
- [x] Setup build pipeline
- [x] Make public
- [x] Run [SQAaaS](https://sqaaas.eosc-synergy.eu/#/auth/full-assessment) and add badge to ReadMe file

**Comment by matthew-morris-cessda** [comment]
Repository created at https://github.com/cessda/coordinate-portal/

A Jenkinsfile has been added and SonarQube settings have been adjusted.

**Comment by matthew-morris-cessda** [comment]
Standard repository content added, build pipeline set up

**Comment by matthew-morris-cessda** [comment]
SQAaaS assessments failing due to dependency issues. I've sent a support request to see if this can be resolved.

**Comment by matthew-morris-cessda** [comment]
SQAaaS assessments run, badges added to README
