### ISSUE TITLE
FSD records are being marked as invalid by the CDC validator

### ISSUE THREAD

**Issue by matthew-morris-cessda** [cessda/cessda.cdc.versions#651]
This issue was reported into the helpdesk:

> Hello again,
> 
> it seems that CESSDA now uses the newest profile version for validation. There is a bug in that version that will be fixed in the next CDC profile version:
> 
> https://github.com/cessda/cessda.metadata.profiles/issues/164
> 
> This issue was discussed with CDC SOs in March[ https://docs.google.com/document/d/1Ex5e9Tn0eihGUpJqFb_EhNVdFPh_iSa4HxtxzrN3kIU/edit](https://docs.google.com/document/d/1Ex5e9Tn0eihGUpJqFb_EhNVdFPh_iSa4HxtxzrN3kIU/edit)
> 
> There was no announcement about CESSDA using a new profile with new mandatory fields in validation so it might be a surprise for other SPs as well.
> 
> Are there other archives in addition to FSD that have now “not valid” xml files because of the bug?
> 
> I’m the person doing the profiles this year so this might now change my work priority.
> 
> Best wishes,
> 
> Katja

**Comment by matthew-morris-cessda** [comment]
@katja-moilanen Should we revert to a previous version of the CMV profiles?

**Comment by katja-moilanen** [comment]
> @katja-moilanen Should we revert to a previous version of the CMV profiles?

I guess it is the fastest solution at this moment @matthew-morris-cessda

**Comment by matthew-morris-cessda** [comment]
Before

`FSD: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml: Validated 1948 records, 1948 invalid`

After:

`FSD: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/1.0.4/profile.xml: Validated 1954 records, 1 invalid`
