### ISSUE TITLE
Release CDC 3.6.0

### ISSUE THREAD

**Issue by KristinaS4** [cessda/cessda.cdc.versions#663]
Release report: https://docs.google.com/document/d/11VczFS6tfqc4-xe9cYGKNbcjD3ndCxFMy7Zfi3X0RAE/edit#heading=h.bxl4rzqycrnr
Release checklist: https://docs.google.com/spreadsheets/d/1en3boDxzgxzkiIltHoWKajnYCbNf8RlvVtphJ3W7R30/edit#gid=202412508

- [x] https://github.com/cessda/cessda.cdc.versions/issues/664
- [x] https://github.com/cessda/cessda.cdc.versions/issues/665
- [x] #666

Expected release date is 18th of June

**Comment by matthew-morris-cessda** [comment]
@KristinaS4  Release ready for approval

**Comment by KristinaS4** [comment]
Great @matthew-morris-cessda  Approved!

**Comment by matthew-morris-cessda** [comment]
CDC 3.6.0 released
