### ISSUE TITLE
Release version information is incorrect

### ISSUE THREAD

**Issue by john-shepherdson** [cessda/cessda.cdc.versions#668]
![Screenshot 2024-06-27 at 11 03 45](https://github.com/cessda/cessda.cdc.versions/assets/107628491/a6787a38-0222-4389-81ae-3d4f118d5dee)

**Comment by KristinaS4** [comment]
I updated the About page (https://github.com/cessda/cessda.cdc.versions/issues/665), not sure why the changes were not implemented.

**Comment by matthew-morris-cessda** [comment]
I don't see any commits relating to #665
