### ISSUE TITLE
Add ORCID iD icon before ORCID iD URL

### ISSUE THREAD

**Issue by markusjt** [cessda/cessda.cdc.versions#677]
Related to #290 in which creator identifier was added.

Katja told me about the guidelines from [ORCID](https://info.orcid.org/documentation/integration-guide/user-experience-display-guidelines/) which specifically mentions that "We don’t allow references to authorized ORCID iDs without an ORCID iD icon".

@MortenSikt Should we use the [green icon or the black icon](https://info.orcid.org/documentation/integration-guide/user-experience-display-guidelines/#The_ORCID_iD_icon)? I feel like black would fit better into CDC but green is more recognizable.

What should we do if instead of metadata specifying type like this:
DDI-C 2.5:
```xml
<ExtLink URI="https://orcid.org/0000-0002-7668-5427" role="PID" title="ORCID">0000-0002-7668-5427</ExtLink>
</AuthEnty>
```
DDI-C 2.6:
```xml
<AuthEnty personalID="0000-0002-7668-5427" typeOfPersonalID="ORCID">Moilanen, Katja</AuthEnty>
```
It doesn't have ORCID specified so it's just:
DDI-C 2.5:
```xml
<ExtLink URI="https://orcid.org/0000-0002-7668-5427" role="PID">0000-0002-7668-5427</ExtLink>
</AuthEnty>
```
DDI-C 2.6
```xml
<AuthEnty personalID="0000-0002-7668-5427">Moilanen, Katja</AuthEnty>
```
Do we still add ORCID iD icon just in case or do we leave it out? Also, currently the identifier type is written before the link but it defaults to "Research Identifier: " if type is not specified but it should probably also just say "ORCID: " if we decide to assume everything is ORCID unless specified otherwise.

**Comment by MortenSikt** [comment]
Go for black for now
