### ISSUE TITLE
Update changelogs for version 3.7.0

### ISSUE THREAD

**Issue by MortenSikt** [cessda/cessda.cdc.versions#682]
Components to update:

- [x] cessda.cdc.osmh-indexer.cmm - DOI 10.5281/zenodo.14056449
- [x] cessda.cdc.searchkit - DOI 10.5281/zenodo.14055702
- [x] cessda.metadata.harvester - no significant changes
- [x] cessda.cmv.console - no significant changes

**Comment by matthew-morris-cessda** [comment]
Changelogs updates
